### ISSUE TITLE
This Script Uses WIN32Dialog.Blob and WIN32Dialog.invalidateAll,which is not contained in win32dialog.dll

### ISSUE THREAD

**Issue by khjxiaogu** [krkrz/Krkr2Compat#2]
Some of the functions uses this two stuff,which creates a large amount of errors.
It should be replaced with other method.

**Comment by miahmie** [comment]
どちらの win32dialog.dll を利用されていますか？
https://github.com/krkrz/krkr2/tree/master/kirikiri2/trunk/kirikiri2/src/plugins/win32/win32dialog
上記ソースでは WIN32Dialog.Blob や invalidateAll が含まれますので今一度ご確認ください。
